# Before Build
init:
  - git config --global core.autocrlf true

# scripts to run before build
before_build:
  - dotnet --info

# Build script
build_script:
  - ps: .\build.ps1 --target=CI

# Tests
test: off

# Branches to build
branches:
  only:
    - develop
    - master
    - main
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
  - tools -> recipe.cake

# Environment configuration
image: Visual Studio 2022

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /\(doc\).*/
